## 多分类和多标签算法

## 多标签分类格式
在多标签学习中，二元分类任务的联合集合用标签二进制指示符数组表示：每个样本是具有二进制值的2d数组形状（n_samples，n_classes）的一行，即非零元素对应于标签的子集。第一个样本中表示标签0 的数组 ，第二个样本中的标签1和2，第三个样本中没有标签。np.array([[1, 0, 0], [0, 1, 1], [0, 0, 0]])<br>
生成多标签数据作为标签集合的列表可能更直观。该MultiLabelBinarizer 变压器可用于标签的集合的集合和指标格式之间的转换。

In [2]:
from sklearn.preprocessing import MultiLabelBinarizer
y = [[ 4], [2], [3], [0], [1]]
MultiLabelBinarizer().fit_transform(y)

array([[0, 0, 0, 0, 1],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0]])

## One-Vs-The-Rest
这个策略，也被称为一对一全部，被执行 OneVsRestClassifier。该策略在于每个类装配一个分类器。对于每个分类器，该类适用于所有其他类。除了其计算效率（仅 需要n_classes分类器）之外，这种方法的一个优点是其可解释性。由于每个类都由一个分类器表示，所以可以通过检查其对应的分类器来获得有关该类的知识。这是最常用的策略，是一个公平的默认选择。
### 多类学习
下面是使用OvR进行多类学习的例子：

In [3]:
from sklearn import datasets
from sklearn.multiclass import OneVsRestClassifier
from sklearn.svm import LinearSVC
iris = datasets.load_iris()
X, y = iris.data, iris.target
OneVsRestClassifier(LinearSVC(random_state=0)).fit(X, y).predict(X)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 1, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

## One-Vs-One
OneVsOneClassifier每对类构造一个分类器。在预测时候，选出最多票数的课程。如果是一个关系（在两个票数相等的两个类别中），则通过对基于二进制分类器计算的成对分类置信水平进行求和来选择具有最高总分类置信度的类。
由于它需要适合分类器，因为它的O（n_classes ^ 2）复杂度，所以这种方法通常比一对一休息慢。然而，该方法对于诸如不能很好地缩放的内核算法的算法可能是有利的 。这是因为每个单独的学习问题只涉及数据的一小部分，而使用一对一休息时，完整的数据集将被使用。n_classes * (n_classes - 1) / 2n_samplesn_classes
### 多类学习
下面是使用OvO进行多类学习的例子：

In [4]:
from sklearn import datasets
from sklearn.multiclass import OneVsOneClassifier
from sklearn.svm import LinearSVC
iris = datasets.load_iris()
X, y = iris.data, iris.target
OneVsOneClassifier(LinearSVC(random_state=0)).fit(X, y).predict(X)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 2, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

## 多输出回归
多输出回归支持可以添加到任何回归 MultiOutputRegressor。该策略包括每个目标拟合一个回归。由于每个目标都由恰好一个回归函数表示，因此可以通过检查其对应的回归函数来获得关于目标的知识。对于 MultiOutputRegressor每个目标，它适合一个回归者，它不能利用目标之间的相关性。
以下是多输出回归的示例：


In [5]:
from sklearn.datasets import make_regression
from sklearn.multioutput import MultiOutputRegressor
from sklearn.ensemble import GradientBoostingRegressor
X, y = make_regression(n_samples=10, n_targets=3, random_state=1)
MultiOutputRegressor(GradientBoostingRegressor(random_state=0)).fit(X, y).predict(X)

array([[-154.75474165, -147.03498585,  -50.03812219],
       [   7.12165031,    5.12914884,  -81.46081961],
       [-187.8948621 , -100.44373091,   13.88978285],
       [-141.62745778,   95.02891072, -191.48204257],
       [  97.03260883,  165.34867495,  139.52003279],
       [ 123.92529176,   21.25719016,   -7.84253   ],
       [-122.25193977,  -85.16443186, -107.12274212],
       [ -30.170388  ,  -94.80956739,   12.16979946],
       [ 140.72667194,  176.50941682,  -17.50447799],
       [ 149.37967282,  -81.15699552,   -5.72850319]])

In [6]:
X

array([[  1.76041518e+00,  -3.91816240e-01,   5.56073510e-01,
         -2.51630386e+00,  -1.16400797e+00,   6.36583409e-01,
         -8.06184817e-01,  -1.83400197e-01,  -1.78791289e+00,
         -1.15498263e+00,   5.10937774e-01,   1.44287693e+00,
          1.81038744e-01,   1.47016034e+00,   9.66539250e-01,
          3.82715174e-01,   1.62091229e+00,   1.89293198e-01,
          1.07343294e-01,   5.13505480e-01,  -1.51045638e+00,
         -2.75293863e-02,   1.28376990e-01,  -7.99547491e-01,
         -2.22414029e-01,   5.48129585e-01,  -1.47656266e+00,
          1.74643509e+00,  -6.74100249e-02,  -1.56573815e+00,
          3.95860270e+00,  -5.39681562e-01,   1.71066184e+00,
         -6.04602969e-01,   1.69380911e+00,  -2.91594596e-01,
          1.01120706e+00,   5.57439453e-01,  -1.11343610e+00,
         -7.31530982e-01,  -1.63744959e+00,  -2.51674208e-01,
          7.13049050e-01,  -4.24492791e-01,   1.30620607e+00,
         -3.09121319e-01,   9.86352180e-01,   1.85300949e+00,
        

In [7]:
X.shape

(10, 100)

In [8]:
y

array([[-154.75925123, -147.04008173,  -50.0391129 ],
       [   7.12196236,    5.12947161,  -81.46271129],
       [-187.90082901, -100.44752664,   13.89261407],
       [-141.63065051,   95.03154575, -191.48634356],
       [  97.03431452,  165.35268762,  139.52452391],
       [ 123.9283255 ,   21.25870198,   -7.84234868],
       [-122.25363653,  -85.16607897, -107.12559788],
       [ -30.17072278,  -94.81208397,   12.17160241],
       [ 140.73115332,  176.51479747,  -17.50467183],
       [ 149.38584071,  -81.15780316,   -5.72757681]])

## 多输出分类
Multioutput分类支持可以添加到任何分类器 MultiOutputClassifier。这个策略包括每个目标的一个分类器。这允许多个目标变量分类。该类的目的是扩展估计器以能够估计在单个X预测矩阵上训练的一系列目标函数（f1，f2，f3 ...，fn），以预测一系列的代表（y1，y2 ，Y3，...，YN）。
以下是多输出分类的示例：


In [9]:
from sklearn.datasets import make_classification
from sklearn.multioutput import MultiOutputClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.utils import shuffle
import numpy as np
X, y1 = make_classification(n_samples=10, n_features=100, n_informative=30, n_classes=3, random_state=1)

In [10]:
X

array([[ -9.34327201e-01,   1.56624579e+00,  -1.00725887e+00,
         -3.08376593e+00,  -4.21430086e+00,   1.16986584e-01,
          4.17638636e-01,   9.00653742e-01,   3.93005059e+00,
         -6.50885358e-01,   1.29279861e-01,   1.63423085e+00,
          4.91320357e-01,   1.14596589e+00,   9.21903246e-01,
         -2.31502687e+00,  -4.84047630e-01,  -4.55542563e-01,
          7.34029572e-01,   1.50469875e+00,   5.82357527e-01,
          1.02239602e+00,   2.12138407e+00,  -1.16327945e+00,
          2.33826928e+00,   6.34323770e-01,  -4.01455641e+00,
          6.01882630e-01,  -6.59967952e-01,   1.04178795e+00,
         -1.28307651e+01,   1.92709640e+00,   1.24955216e+00,
          1.29391297e+00,  -1.85151553e-01,  -9.00264870e-02,
         -4.78124907e-01,   1.65233362e+00,   4.37764479e-01,
          1.67131175e+00,  -2.20026617e-02,   2.35819835e-02,
          2.32405079e-01,  -6.08059465e-01,   6.24715074e-01,
          5.96586474e-01,  -4.72840351e+00,  -1.04025224e+00,
        

In [11]:
y1

array([2, 1, 2, 0, 0, 0, 1, 1, 0, 2])

In [12]:
y2 = shuffle(y1, random_state=1)
print(y2)
y3 = shuffle(y1, random_state=2)
print(y3)

[2 2 1 0 2 0 1 1 0 0]
[0 1 0 2 1 2 0 1 2 0]


In [13]:
Y = np.vstack((y1, y2, y3)).T

In [14]:
Y

array([[2, 2, 0],
       [1, 2, 1],
       [2, 1, 0],
       [0, 0, 2],
       [0, 2, 1],
       [0, 0, 2],
       [1, 1, 0],
       [1, 1, 1],
       [0, 0, 2],
       [2, 0, 0]])

In [15]:
n_samples, n_features = X.shape # 10,100
n_outputs = Y.shape[1] # 3
n_classes = 3
forest = RandomForestClassifier(n_estimators=100, random_state=1)
multi_target_forest = MultiOutputClassifier(forest, n_jobs=-1)
multi_target_forest.fit(X, Y).predict(X)

array([[2, 2, 0],
       [1, 2, 1],
       [2, 1, 0],
       [0, 0, 2],
       [0, 2, 1],
       [0, 0, 2],
       [1, 1, 0],
       [1, 1, 1],
       [0, 0, 2],
       [2, 0, 0]])