## tf.slice()
* 函数原型 tf.slice(inputs,begin,size,name='')
* 用途：从inputs中抽取部分内容
     inputs：可以是list,array,tensor
     begin：n维列表，begin[i] 表示从inputs中第i维抽取数据时，相对0的起始偏移量，      也就是从第i维的begin[i]开始抽取数据
     size：n维列表，size[i]表示要抽取的第i维元素的数目
     有几个关系式如下:
     * i in [0,n]
     * tf.shape(inputs)[0]=len(begin)=len(size)
     * begin[i]>=0   抽取第i维元素的起始位置要大于等于0
     * begin[i]+size[i]<=tf.shape(inputs)[i]



In [6]:
import tensorflow as tf  
import numpy as np  
x=[[1,2,3],[4,5,6]]  
y=np.arange(24).reshape([2,3,4])  
z=tf.constant([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]], [[13,14,15],[16,17,18]]])
sess=tf.Session()  
begin_x=[1,0]        #第一个1，决定了从x的第二行[4,5,6]开始，第二个0，决定了从[4,5,6] 中的4开始抽取  
size_x=[1,2]           # 第一个1决定了，从第二行以起始位置抽取1行，也就是只抽取[4,5,6] 这一行，在这一行中从4开始抽取2个元素  
out=tf.slice(x,begin_x,size_x)  
print(x)
print(sess.run(out))  #  结果:[[4 5]]  
  
begin_y=[1,0,0]  
size_y=[1,2,3]  
out=tf.slice(y,begin_y,size_y)     
print(y)
print(sess.run(out))  # 结果:[[[12 13 14] [16 17 18]]]  
  
begin_z=[0,1,1]  
size_z=[-1,1,2]   
out=tf.slice(z,begin_z,size_z)  
print(z)
print(sess.run(out))  # size[i]=-1 表示第i维从begin[i]剩余的元素都要被抽取，结果：[[[ 5  6]] [[11 12]] [[17 18]]]  


[[1, 2, 3], [4, 5, 6]]
[[4 5]]
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
[[[12 13 14]
  [16 17 18]]]
Tensor("Const_1:0", shape=(3, 2, 3), dtype=int32)
[[[ 5  6]]

 [[11 12]]

 [[17 18]]]
