In [6]:
import tensorflow as tf
import numpy as np

## tf.transpose()
tf.transpose(input, [dimension_1, dimenaion_2,..,dimension_n])
这个函数主要适用于交换输入张量的不同维度用的，如果输入张量是二维，就相当是转置。dimension_n是整数，如果张量是三维，就是用0,1,2来表示。这个列表里的每个数对应相应的维度。如果是[2,1,0]，就把输入张量的第三维度和第一维度交换。

In [13]:
x_in=[[1,2,3],[4,5,6]]
with tf.Session() as sess:
    print(sess.run(tf.transpose(x_in,[1,0])))
y_in=np.array([[[1,2,3],[4,5,6]]])
print(y_in.shape)
with tf.Session() as sess:
    print(y_in)
    print(sess.run(tf.transpose(y_in,[1,2,0])))

[[1 4]
 [2 5]
 [3 6]]
(1, 2, 3)
[[[1 2 3]
  [4 5 6]]]
[[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]]
